Fix crash seen in hip_sycl_interop samples
CHIP-SPV/chip-spv pull request #260
Opened 2022-11-18 17:47 UTC by Sarbojit2019

2022-11-18 18:19 UTC, Sarbojit2019 commented
PR has fix for #258 and #253

2022-11-18 20:20 UTC, pvelesko requested changes

2022-11-18 20:20 UTC, pvelesko commented on samples/hip_sycl_interop/hip_sycl_interop.cpp
> +  std::string envVar(val);
the runtime will default to something for all other tests so we should query the runtime to get this value rather than reading the env.

2022-11-18 20:40 UTC, pvelesko commented
sycl_hip samples are still segfaulting but hip_sycl is now passing.

2022-11-30 15:08 UTC, pvelesko approved these changes

2022-11-30 15:08 UTC, merged