CI Upgrade 2
CHIP-SPV/chip-spv pull request #333
Opened 2023-01-26 10:56 UTC by pvelesko

* Load/unload device from the driver before each test

2023-01-26 14:04 UTC, pjaaskel requested changes

2023-01-26 14:04 UTC, pjaaskel commented on cmake/UnitTests.cmake
> +list(APPEND POCL_LEVEL0_FAILED_TESTS " ")
I believe your are testing with the CPU driver still? PoCL-L0 likely fails a lot more tests currently. Best name this POCL_CPU_FAILED_TESTS as we will add also POCL_LEVEL0_FAILED_TESTS when most of the tests pass?

2023-01-26 14:04 UTC, pjaaskel commented on scripts/check_unit_tests.sh
> +# Test OpenCL CPU
Intel OpenCL CPU

2023-01-27 07:57 UTC, pjaaskel approved these changes
LGTM

2023-01-27 08:13 UTC, pvelesko commented
For some reason sycl test is failing when run through CI

2023-01-27 09:42 UTC, pvelesko commented
@pjaaskel I added a python script for running tests - let me know if it works for you. 

Still need to investigate why the sycl test segfaults upon exit but only when run through CI.

2023-01-30 12:06 UTC, merged